apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2025-02-23T00:52:49Z"
  generation: 1
  labels:
    app: binarycalculator-deployment
  name: binarycalculator-deployment
  namespace: default
  resourceVersion: "13342"
  uid: f67fe035-d7a9-4175-91c1-eee024a5a70a
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: binarycalculator-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: binarycalculator-deployment
    spec:
      containers:
      - image: northamerica-northeast2-docker.pkg.dev/binary-calculator-451800/sofe3980u/binarycalculator
        imagePullPolicy: Always
        name: binarycalculator
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-02-23T00:52:58Z"
    lastUpdateTime: "2025-02-23T00:52:58Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-02-23T00:52:50Z"
    lastUpdateTime: "2025-02-23T00:52:58Z"
    message: ReplicaSet "binarycalculator-deployment-7779b6f797" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
